language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install -r requirements.txt
script: pytest
env:
  global:
  - secure: NyoNvhjXuoHUEwzuJQmobvzf0BX9+PvhpYTiWq94a/WyI2baxOTl3/1QNIGk9EeJsotlZMvx20vW1IaDAdJa7cvB+iqmejmoqemTgNRuM8jtTu2bwzsMtm7dgQI3KQo8FHNtwVsIA8EP6+7kAbnwqiujRsaKNXwHTCsKeQs6/9o=
  - secure: V/G4QJZTtLvyF8gtRbwz+Z5gdQSuRrERkrxKvlUDDHI7UV2054mJ8aYA9nXeLjqni72pPE1fvZ0Cg1gl/hEtk+697oD1otIiP7sq/YA5d7DJMLglzhS/w8SeJ9pydXwrH46jctCkFvr8J4uAU3mebVCeZzkO59yiOEOo47MXfPc=
  - secure: Xx4BE/hdJ54NK7NVB/LSdkRMdzRIjdwZGwJTdskCS7meSQpczA7DzGYOGzdw7jNpwzv9SvzAwsgzpkGvDOSyaOvgemo2CmPW52WUD7YPI4FgYOzTIikBMitXcXWkevvBMXw+6vzbp+6RaLs4iu9csRmEvTvgOajqQeutrdqeUSo=
